### PR TITLE
Reverse bit patterns for SEG7_FONT

### LINKED ISSUE #129: SEG7_FONT up side down
#### Type of Raspberry Pi
RPI1B (not plus)

#### Linux Kernel version
4.9.80+ #1098 Fri Mar 9 18:51:28 GMT 2018 armv6l GNU/Linux

#### Expected behaviour
Display is showing the time and is made at 19:12:32

image

#### Actual behaviour
the numbers 96752 are upsite down, does not happen with other fonts

### Running code
```python
from luma.core.interface.serial import spi, noop
from luma.core.render import canvas
from luma.led_matrix.device import max7219
from luma.core.legacy.font import proportional, LCD_FONT, CP437_FONT, TINY_FONT, SINCLAIR_FONT, SEG7_FONT
from luma.core.legacy import text
import time
import datetime

serial = spi(port=0, device=0, gpio=noop())
device = max7219(serial, cascaded=5, block_orientation=-90)
while 1:
        with canvas(device) as draw:
                now = datetime.datetime.now()
                t = now.strftime('%H:%M:%S')
                text(draw, (0, 0), t, fill="white", font=(SEG7_FONT))
        time.sleep(0.1)
```

### PR DESCRIPTION
**Pull request by rm-hull**
Hacky script used to reverse bit patterns:

```python
#!/usr/bin/env python

from luma.core.legacy.font import SEG7_FONT


def transform(bit_pattern):
    a = bit_pattern >> 7 & 0x01
    b = bit_pattern >> 6 & 0x01
    c = bit_pattern >> 5 & 0x01
    d = bit_pattern >> 4 & 0x01
    e = bit_pattern >> 3 & 0x01
    f = bit_pattern >> 2 & 0x01
    g = bit_pattern >> 1 & 0x01
    h = bit_pattern >> 0 & 0x01
    return a | b << 1 | c << 2 | d << 3 | e << 4 | f << 5 | g << 6 | h << 7


for i, bitmaps in enumerate(SEG7_FONT):
    if 32 <= i < 127:
        ch = "'{0}'".format(chr(i))
    else:
        ch = "0x{0:02X}".format(i)

    corrected = ', '.join(['0x{0:02X}'.format(transform(n)) for n in bitmaps])
    print '    [{0}],  # {1}'.format(corrected, ch)
```

Emulator now shows fonts right way up (running luma.examples weather.py):

screen shot 2018-03-27 at 21 33 37

Fixes #129

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull can we make a test for this (that compares to an image)?

**Comment by rm-hull** [comment]
Good call @thijstriemstra, zero is malformed:

screen shot 2018-03-28 at 00 14 55

**Comment by thijstriemstra** [comment]
looks great, thanks.

**Comment by rm-hull** [comment]
These are bitmapped fonts so the size is fixed at 8 pixels high.

**Pull request merged**
