### PR TITLE
use time.perf_counter

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #204

### CODE REVIEW

**Review by rm-hull — DISMISSED** [review]

**Comment by thijstriemstra** [comment]
@rm-hull I changed the calls to `perf_counter_ns`. `perf_counter_ns` seems to be a more suitable api for what we're trying to use it (available since python 3.3 so that explains why we didn't use it earlier). The tests do not really account for nano or milliseconds so they still pass. Question is, should we change the APIs and expect nanoseconds, where it expected seconds before, or should the api stay the same and we will do the nanosecond/second conversion for the user?

**Comment by thijstriemstra** [comment]
@rm-hull I wanted to include this and a few other backward incompatible changes in v2.0. Isn't v2.0 currently breaking all other sub-projects? I'm confused.

**Comment by rm-hull** [comment]
Sorry the notification for your last msg ended up in spam. The framebuffer changes would've only affected certain LCD and OLED devices.

**Comment by rm-hull** [comment]
These changes shouldn't be breaking should they? We are just using a different internal mechanism to record time more accurately. The interface still stays the same doesn't it?

**Review by rm-hull — COMMENTED** [review]
Time.perf_counter_ns() returns an integer which is in nanoseconds according to https://docs.python.org/3/library/time.html#time.perf_counter_ns.

So the elapsed time will be in nanoseconds, which if called the sleep at line 207 would be a very long time. If we are to use this function, tit should divide by 1e9 to get the correct number of seconds presumably?

... or just use time.perf_counter() ?

**Comment by rm-hull** [comment]
And if we went with perf_counter(), then it would work with python 3.6 too

**Comment by thijstriemstra** [comment]
But perf_counter doesn't have the additional precision aka it'll start drifting after only 104 days.

**Comment by thijstriemstra** [comment]
> But perf_counter doesn't have the additional precision aka it'll start drifting after only 104 days.

Let's start with `perf_counter` and improve with more precision later.

**Review by rm-hull — APPROVED** [review]

**Pull request merged**
