### PR TITLE
Allow alternative RPi.GPIO implementations

### PR DESCRIPTION
**Pull request by rm-hull**
Allows an alternative GPIO implementation to be supplied on the command line, e.g. for Orange Pi:

    $ sudo python examples/colors.py -f conf/st7735.conf --gpio=OPi.GPIO --spi-port=1

@sgjava & @combs - this should work for your C.H.I.P. board too, by setting `--gpio=CHIP_IO.GPIO`

### CODE REVIEW

**Comment by sgjava** [comment]
Coolio, going to try tonight when I get home!

**Comment by rm-hull** [comment]
A new release *0.7.5* has been pushed to pypi with this change in, so if you `$ sudo pip install -U luma.core`

**Comment by sgjava** [comment]
Will do!

**Comment by sgjava** [comment]
OK, I tried this on my CHIP:

`sudo python examples/invaders.py --display ssd1306 --interface spi --spi-device 0 --spi-port 32766 --gpio=CHIP_IO --gpio-data-command 133 --gpio-reset 132`

and I get:

```
Traceback (most recent call last):
  File "examples/invaders.py", line 189, in <module>
    device = get_device()
  File "/home/chip/luma.examples/examples/demo_opts.py", line 51, in get_device
    device = cmdline.create_device(args)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/cmdline.py", line 129, in create_device
    device = Device(Serial(), **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/luma/core/cmdline.py", line 104, in spi
    GPIO.setmode(GPIO.BCM)
AttributeError: 'module' object has no attribute 'setmode'
```
I updated luma.core and luma.examples.

**Comment by sgjava** [comment]
CHIP_IO uses strings for ports, so this works:

```
serial = spi(port=32766, device=0, gpio=CHIP_IO.GPIO, bcm_DC="CSID1", bcm_RST="CSID0")
device = ssd1306(serial)
```

but this doesn't:

`python examples/invaders.py  --display ssd1306 --interface spi --spi-device 0 --spi-port 32766 --gpio CHIP_IO.GPIO --gpio-data-command 133 --gpio-reset 132`

```
Traceback (most recent call last):
  File "examples/invaders.py", line 189, in <module>
    device = get_device()
  File "/home/chip/luma.examples/examples/demo_opts.py", line 51, in get_device
    device = cmdline.create_device(args)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/cmdline.py", line 129, in create_device
    device = Device(Serial(), **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/luma/core/cmdline.py", line 114, in spi
    gpio=self.gpio or GPIO)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 267, in __init__
    bitbang.__init__(self, gpio, transfer_size, DC=gpio_DC, RST=gpio_RST)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 155, in __init__
    self._DC = self._configure(kwargs.get("DC"))
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 166, in _configure
    self._gpio.setup(pin, self._gpio.OUT)
TypeError: argument 1 must be string, not int
```
and this doesn't:

`python examples/invaders.py  --display ssd1306 --interface spi --spi-device 0 --spi-port 32766 --gpio CHIP_IO.GPIO --gpio-data-command CSID1 --gpio-reset CSID0`

`invaders.py: error: argument --gpio-data-command: invalid int value: 'CSID1'`

I believe this is the way the CHIP handles GPIO (string vs. int).

**Comment by rm-hull** [comment]
Does this work?

```python
serial = spi(port=32766, device=0, gpio=CHIP_IO.GPIO, gpio_DC="133", gpio_RST="132")
device = ssd1306(serial)
```

I will try and make it support strings, but will check that the RPi.GPIO supports that first though

**Comment by rm-hull** [comment]
Unfortunately, RPi.GPIO won't accept strings: 

```
$ python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import RPi.GPIO as GPIO
>>> GPIO.setmode(GPIO.BCM)
>>> GPIO.setup(18, GPIO.OUT)
>>> GPIO.setup("18", GPIO.OUT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Channel must be an integer or list/tuple of integers
```

**Comment by sgjava** [comment]
Traceback (most recent call last):
  File "spihello.py", line 7, in <module>
    serial = spi(port=32766, device=0, gpio=CHIP_IO.GPIO, gpio_DC="133", gpio_RST="132")
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 267, in __init__
    bitbang.__init__(self, gpio, transfer_size, DC=gpio_DC, RST=gpio_RST)
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 155, in __init__
    self._DC = self._configure(kwargs.get("DC"))
  File "/usr/local/lib/python2.7/dist-packages/luma/core/serial.py", line 166, in _configure
    self._gpio.setup(pin, self._gpio.OUT)
ValueError: Invalid channel 133. ()

I was getting the same error with the ODROID C1 and its RPi.GPIO replacement, but I think that was a different issue. Any chance on abstracting or wrapping the class that does the GPIO stuff? Looks like CHIP_IO has an open issue about specifying pin numbers https://github.com/xtacocorex/CHIP_IO/issues/65

**Comment by xtacocorex** [comment]
CHIP_IO has been updated to enable control with the sysfs pin numbers, so hacking things to get this stuff to work should be resolved.  I don't have any displays to test this stuff out, so if there are issues with CHIP_IO, flag the issues on my repo and I'll see what I can do.

**Comment by thijstriemstra** [comment]
> CHIP_IO has been updated to enable control with the sysfs pin numbers, so hacking things to get this stuff to work should be resolved.

@xtacocorex any link to documentation for that for future reference?

**Comment by xtacocorex** [comment]
https://xtacocorex.github.io/CHIP_IO/gpio.html

I forgot to update the documentation to show examples with the pin numbers, will do that soon.

**Pull request merged**
