### PR TITLE
release: 2.4.0

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I don't understand why github actions still wants to run the Python 3.6 process, even when it's not instructed to (any longer) 👎🏼 is there any cache or something that needs to be cleaned? Some of the checks in the list above have the label 'required' even though I don't see where this is specified...

**Comment by thijstriemstra** [comment]
Build error is false broken link and can be ignored: https://github.com/rm-hull/luma.core/actions/runs/3261283157/jobs/5355843122#step:8:133

**Review by rm-hull — APPROVED** [review]

**Comment by thijstriemstra** [comment]
hi @rm-hull can you tag this release so it gets published to pypi?

**Comment by rm-hull** [comment]
Well, i tagged it, and pushed, the job eventually ran https://github.com/rm-hull/luma.core/actions/runs/3276977398, but didnt actually publish

**Comment by rm-hull** [comment]
https://pypi.org/project/luma.core/2.4.0/ released manually

**Pull request merged**
