### PR TITLE
Support accented characters

### LINKED ISSUE #122: UTF-8 support in terminal for Python 2
When I try to draw a text containing a unicode character, I get the following error:
```
error from callback <function on_message at 0xb64edef0>: 'ascii' codec can't encode character u'\u015b' in position 17: ordinal not in range(128)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 269, in _callback
    callback(self, *args)
  File "pushbullet.py", line 48, in on_message
    term.println(title)
  File "/pishare/src/luma.core/luma/core/virtual.py", line 268, in println
    self.puts(text)
  File "/pishare/src/luma.core/luma/core/virtual.py", line 282, in puts
    for method, args in ansi_color.find_directives(text, self):
  File "/pishare/src/luma.core/luma/core/ansi_color.py", line 103, in find_directives
    for directive in parse_str(text):
  File "/pishare/src/luma.core/luma/core/ansi_color.py", line 62, in parse_str
    text = str(text)
```

Are there any plans to support encodings other than ASCII? Or is that a limitation of the PIL library?

### PR DESCRIPTION
**Pull request by rm-hull**
This PR will attempt to fix the regex bug and python 2 compatibility mentioned in issue https://github.com/rm-hull/luma.oled/issues/161

fixes #122

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull still a WIP right?

**Comment by rm-hull** [comment]
yeah, mostly things been on hold (I've had a loooong summer holiday) - will try and mop up some issues and PRs over the coming weeks.

**Comment by thijstriemstra** [comment]
@rm-hull anything I can do to help here?

**Comment by rm-hull** [comment]
I've been a bit sidetracked with work commitments over the past few months; if you can have a look that would be great

**Comment by thijstriemstra** [comment]
@rm-hull what are remaining issues? py3 support?

**Comment by thijstriemstra** [comment]
@rm-hull I managed to get everything green again. Removing [this line](https://github.com/rm-hull/luma.core/pull/93/files#diff-46b6efcd6962ee05cf0a651b2b3d7887L62) was key as well as adding the `u` prefix when testing on Python 2.7.

**Comment by rm-hull** [comment]
1.7.1 released! 

🎉

**Pull request merged**
