### PR TITLE
Remove redundant document requirements

### LINKED ISSUE #31: Remove  luma.core/doc/requirements.txt
it mentions something about pygame that we don't use here.

### PR DESCRIPTION
**Pull request by thijstriemstra**
no longer needed (fixes #31)

### CODE REVIEW

**Comment by thijstriemstra** [comment]
but i think you'll have to tell readthedocs as well?

**Comment by rm-hull** [comment]
erg.... Virtually = virtualenv (Autocomplete)

**Comment by rm-hull** [comment]
@thijstriemstra - I updated the settings on readthedocs so that it doesnt read `doc/requirements.txt` and it still fails. Can you see this link: https://readthedocs.org/projects/luma-core/builds/5078903/ - it has reverted back to using an older version of sphinx because of the missing requirements

**Comment by thijstriemstra** [comment]
It's taking quite some time to upgrade to Sphinx 1.5.2: https://github.com/rtfd/readthedocs.org/issues/2548

**Comment by thijstriemstra** [comment]
Well, it should be ok now. Waiting for travis, can you check the rtd build @rm-hull?

**Comment by rm-hull** [comment]
* https://readthedocs.org/projects/luma-core/builds/5081395/
* http://luma-core.readthedocs.io/en/doc-req/

Its looking :+1:

**Comment by thijstriemstra** [comment]
Nice! Will merge after travis is ready.

**Pull request merged**
