### PR TITLE
Catch input/output errors

### LINKED ISSUE #5: OSError: [Errno 5] Input/output error
Was getting this traceback when there wasn't any I2C device connected to the RPi:

```
$ python examples/3d_box.py -i i2c
...
3d_box.py: error: [Errno 5] Input/output error
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/pi/projects/pi-test/luma.core/luma/core/device.py", line 70, in cleanup
    self.hide()
  File "/home/pi/projects/pi-test/luma.core/luma/core/device.py", line 53, in hide
    self.command(self._const.DISPLAYOFF)
  File "/home/pi/projects/pi-test/luma.core/luma/core/device.py", line 32, in command
    self._serial_interface.command(*cmd)
  File "/home/pi/projects/pi-test/luma.core/luma/core/serial.py", line 63, in command
    self._bus.write_i2c_block_data(self._addr, self._cmd_mode, list(cmd))
  File "/home/pi/.virtualenvs/pi-test/lib/python3.4/site-packages/smbus2/smbus2.py", line 274, in write_i2c_block_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 5] Input/output error
```

I thought this `OSError` business was already fixed before; it should throw a devicenotfound error..

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #5, #29

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Want to add tests before merging it.

**Comment by thijstriemstra** [comment]
@rm-hull I was still working on that decorator for rpi.gpio and spidev ;) but they work..

**Comment by rm-hull** [comment]
oops ....

**Comment by thijstriemstra** [comment]
So basically it adds a __rpi_gpio__ or __spidev__ method to any class. This could also be used in lcd.aux for example.

**Comment by thijstriemstra** [comment]
because I don't want to implement the same error handling in every library.

**Pull request merged**
