### PR TITLE
Drop support for Python 3.6

### LINKED ISSUE #256: Pillow 10 deprecation warnings
```
tests/test_character.py::test_setter_getter
  /home/runner/work/luma.core/luma.core/luma/core/virtual.py:607: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
    buf = ''.join([i if i == '\n' or self.font.getsize(i)[0] > 0 else self._undefined for i in buf])

tests/test_terminal.py: 10 warnings
  /home/runner/work/luma.core/luma.core/luma/core/virtual.py:226: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
    w, h = self.font.getsize(chr(i))

tests/test_terminal.py: 10 warnings
  /home/runner/work/luma.core/luma.core/luma/core/virtual.py:327: DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
    w = self.font.getsize(char)[0]
```

See https://github.com/python-pillow/Pillow/pull/6556/files

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #256

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I'm still working on the pillow deprecation stuff, I'll put it back up for review once I'm done.

**Comment by thijstriemstra** [comment]
I've fixed the deprecation warnings by using Pillow >= 9.2.0 methods. I guess we also want to support older versions of Pillow @rm-hull?

**Comment by rm-hull** [comment]
If 9.2 is latest, and pillow recommends using that, let's not support older versions if it makes life difficult

**Review by rm-hull — APPROVED** [review]

**Comment by thijstriemstra** [comment]
I've also added support for native namespace packages (because the other method is deprecated), see https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages for details.

When luma.core 2.4.0 is released, the other sub-projects can also be released (not other way around) and ideally those sub-project releases happen all on the same day. This because the namespace packaging has changed and I think the sub-projects will not be able to be compatible with depending on luma.core 2.4.0.

Related prs:

- https://github.com/rm-hull/luma.lcd/pull/158
- https://github.com/rm-hull/luma.led_matrix/pull/281
- https://github.com/rm-hull/luma.oled/pull/349

**Review by rm-hull — APPROVED** [review]

**Comment by rm-hull** [comment]
I'll spend some time tomorrow releasing - many thanks for taking the time to update these @thijstriemstra

**Comment by rm-hull** [comment]
They're still "work in progress" .. is that intentional or good to be merged?

**Comment by thijstriemstra** [comment]
> They're still "work in progress" .. is that intentional or good to be merged?

This is intentional, I'll ping you when I think it's ready.

**Comment by thijstriemstra** [comment]
I can't seem to merge this because of a false python 3.6 test it's waiting for (which we remove with this pr). Can you merge this @rm-hull?

**Pull request merged**
